ALTER TABLE  `Login` ADD  `last_login` DATE NULL DEFAULT NULL;
RENAME TABLE  `db9_aegee_pl`.`Login` TO  `db9_aegee_pl`.`users` ;
ALTER TABLE  `users` CHANGE  `login_id`  `id` INT( 10 ) NOT NULL AUTO_INCREMENT COMMENT  'id loginu';
ALTER TABLE  `users` ADD  `session_id` VARCHAR( 256 ) NULL DEFAULT NULL;
RENAME TABLE  `db9_aegee_pl`.`Members` TO  `db9_aegee_pl`.`members` ;
ALTER TABLE `members` DROP `pr`;
ALTER TABLE `members` DROP `hr`;
ALTER TABLE `members` DROP `fr`;
ALTER TABLE `members` DROP `it`;
RENAME TABLE  `db9_aegee_pl`.`Payments` TO  `db9_aegee_pl`.`payments` ;
ALTER TABLE `payments` CHANGE `expiration_date` `expirationDate` DATE NOT NULL COMMENT 'Data wygaśnięcia składki';
ALTER TABLE `members` DROP FOREIGN KEY `members_ibfk_1`;
ALTER TABLE `members` CHANGE `mentor_id` `mentorId` INT(10) NOT NULL DEFAULT '0' COMMENT 'ID mentora. ID = 0 oznacza, że członek jest mentorem.';
ALTER TABLE `members` ADD CONSTRAINT `members_ibfk_1` FOREIGN KEY (mentorId) REFERENCES `members`(id);
ALTER TABLE `users` DROP FOREIGN KEY `users_ibfk_1`;
ALTER TABLE `users` CHANGE `member_id` `memberId` INT(10) NOT NULL COMMENT 'id użytkownika';
ALTER TABLE `users` ADD CONSTRAINT `users_ibfk_1` FOREIGN KEY (memberId) REFERENCES `members`(id);
ALTER TABLE `users` CHANGE `last_login` `lastLogin` DATE NULL DEFAULT NULL;
ALTER TABLE `users` CHANGE `session_id` `sessionId` VARCHAR(256) CHARACTER SET utf8 COLLATE utf8_polish_ci NULL DEFAULT NULL;
ALTER TABLE `users` CHANGE `lastLogin` `lastLogin` DATETIME NULL DEFAULT NULL;
ALTER TABLE `payments` DROP FOREIGN KEY `payments_ibfk_1`;
ALTER TABLE `payments` CHANGE `member_id` `memberId` INT(10) NOT NULL COMMENT 'Użytkownik, który opłacił składkę';
ALTER TABLE `payments` ADD CONSTRAINT `payments_ibfk_1` FOREIGN KEY (memberId) REFERENCES `members`(id);
ALTER TABLE `payments` CHANGE `date` `paymentDate` DATE NOT NULL COMMENT 'Data płatności składki';
ALTER TABLE `payments` CHANGE `year` `year` YEAR(4) NULL;
ALTER TABLE `payments` CHANGE `auditCD` `auditCD` DATETIME NOT NULL COMMENT 'Data wpisu do bazy';